/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <stdio.h>
#include <time.h>

int choosing[CNT_CLIENTS];
int number[CNT_CLIENTS];
#define TIMEOUT 1
int last_num = 0;

int *
get_number_1_svc(void *argp, struct svc_req *rqstp) {
    static int result = 0;
    int i = result++;
    number[i] = result;

    printf("give number %d to client %d\n", number[i], i);

    return &number[i];
}


struct BAKERY *
service_1_svc(struct BAKERY *argp, struct svc_req *rqstp) {
    static struct BAKERY result;
    for (int j = 0; j < CNT_CLIENTS; ++j) {
        clock_t start = clock(), end;
        while ((number[j] > 0) && (number[j] < number[argp->num - 1])) {
            if ((clock() - start) / CLOCKS_PER_SEC > TIMEOUT)
                break;
        }
    }
    switch (argp->op) {
        case ADD:
            result.res = argp->arg1 + argp->arg2;
            break;
        case SUB:
            result.res = argp->arg1 - argp->arg2;
            break;
        case MUL:
            result.res = argp->arg1 * argp->arg2;
            break;
        case DIV:
            if (argp->arg2 == 0) {
                printf("Error: division by zero!\n");
                return NULL;
            } else
                result.res = argp->arg1 / argp->arg2;
            break;
        default:
            return NULL;
    }
    last_num = argp->num;
    number[argp->num - 1] = 0;
    for (int i = 0; i < CNT_CLIENTS; ++i)
        if (number[i] > 0)
            return &result;
    last_num = 0;
    return &result;
}
