/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bakery.h"
#include <time.h>
#include <unistd.h>
#include "stdio.h"


void
bakery_prog_1(char *host) {
    CLIENT *clnt;
    int *result_1;
    char *get_number_1_arg;
    struct BAKERY *result_2;
    struct BAKERY service_1_arg;

#ifndef    DEBUG
    clnt = clnt_create(host, BAKERY_PROG, BAKERY_VER, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
#endif    /* DEBUG */

    srand(time(0));
    sleep(rand() % 2 + 1);

    time_t time_1 = clock();
    result_1 = get_number_1((void *) &get_number_1_arg, clnt);
    if (result_1 == (int *) NULL) {
        clnt_perror(clnt, "call failed");
        exit(1);
    }
    time_1 = clock() - time_1;
    service_1_arg.num = *result_1;

    printf("num = %2d\n", *result_1);

    service_1_arg.arg1 = (float) rand() / RAND_MAX * 100 - 50;
    service_1_arg.arg2 = (float) rand() / RAND_MAX * 100 - 50;
    service_1_arg.op = rand() % 4;


    sleep(rand() % 5);
    time_t time_2 = clock();
    result_2 = service_1(&service_1_arg, clnt);
    if (result_2 == (struct BAKERY *) NULL) {
        clnt_perror(clnt, "call failed");
        exit(1);
    }
    time_2 = clock() - time_2;
    printf("%.2f ", service_1_arg.arg1);
    switch (service_1_arg.op) {
        case ADD:
            printf("+ ");
            break;
        case SUB:
            printf("- ");
            break;
        case MUL:
            printf("* ");
            break;
        case DIV:
            printf("/ ");
            break;
        default:
            break;
    }
    printf("%.2f = %.2f\n", service_1_arg.arg2, result_2->res);
    printf("total time = %lf sec\n", (double) (time_2 + time_1) / CLOCKS_PER_SEC);
    clnt_destroy (clnt);
}

int
main(int argc, char *argv[]) {
    char *host;

    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    while (1)
        bakery_prog_1(host);
    exit(0);
}
