/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "prod_cons.h"

bool_t
xdr_prod_cons (XDR *xdrs, prod_cons *objp)
{
	register int32_t *buf;

	 if (!xdr_char (xdrs, &objp->type))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->result))
		 return FALSE;
	return TRUE;
}
