/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "prod_cons.h"
#include <stdlib.h>
#include <time.h>
#include <stdio.h>


void
producer_consumer_prog_1(char *host) {
    sleep(rand() % 2);
    CLIENT *clnt;
    enum clnt_stat retval_1;
    char result_1;
    int service_1_arg;

    clnt = clnt_create(host, producer_consumer_prog, producer_consumer_ver, "udp");
    if (clnt == NULL) {
        clnt_pcreateerror(host);
        exit(1);
    }
    service_1_arg = PROD;
    printf("%s created\n", (service_1_arg == PROD ? "Producer" : "Consumer"));
    retval_1 = service_1(&service_1_arg, &result_1, clnt);
    if (retval_1 != RPC_SUCCESS) {
        clnt_perror(clnt, "call failed");
    }
    printf("%s %c\n", (service_1_arg == PROD ? "Produced" : "Consumed"), result_1);
    clnt_destroy(clnt);
}


int
main(int argc, char *argv[]) {
    char *host;

    if (argc < 2) {
        printf("usage: %s server_host\n", argv[0]);
        exit(1);
    }
    host = argv[1];
    while (1)
        producer_consumer_prog_1(host);
    exit(0);
}
