/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
#include <unistd.h> 

int cur_numb = 0;
int number = 0;
int flag = 0;
int *
get_num_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;
	result = number;
	number++;
	return &result;
}

struct CALCULATOR *
calculator_proc_1_svc(struct CALCULATOR *argp, struct svc_req *rqstp)
{
	static struct CALCULATOR  result;
	if (result.number == cur_numb)
	{
		switch(argp->op)
		{
			case ADD:
				result.result = argp->arg1 + argp->arg2;
				break;
			case SUB:
				result.result = argp->arg1 - argp->arg2;
				break;
			case MUL:
				result.result = argp->arg1 * argp->arg2;
				break;
			case DIV:
				if (argp->arg2 == 0)
				{
					printf("Error: division by zero!\n");
					result.result = 0; // исправить
					result.return_code = 0;
				}
				else
					result.result = argp->arg1 / argp->arg2;
				break;
			default:
				break;
		}
		printf("result %.2f, number %d\n", result.result, argp->number);
		result.return_code = 0;
		cur_numb++;
	}
	else if (result.number < cur_numb)
	{
		printf("too early\n");
		result.return_code = 1;
	}
	else
	{
		printf("too late\n");
		result.return_code = 2;
	}
	return &result;
}
