/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define ADD 0
#define SUB 1
#define MUL 2
#define DIV 3

struct CALCULATOR {
	int op;
	float arg1;
	float arg2;
	float result;
	int number;
	int return_code;
};
typedef struct CALCULATOR CALCULATOR;

#define CALCULATOR_PROG 0x20000001
#define CALCULATOR_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_NUM 1
extern  int * get_num_1(void *, CLIENT *);
extern  int * get_num_1_svc(void *, struct svc_req *);
#define CALCULATOR_PROC 2
extern  struct CALCULATOR * calculator_proc_1(struct CALCULATOR *, CLIENT *);
extern  struct CALCULATOR * calculator_proc_1_svc(struct CALCULATOR *, struct svc_req *);
extern int calculator_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_NUM 1
extern  int * get_num_1();
extern  int * get_num_1_svc();
#define CALCULATOR_PROC 2
extern  struct CALCULATOR * calculator_proc_1();
extern  struct CALCULATOR * calculator_proc_1_svc();
extern int calculator_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_CALCULATOR (XDR *, CALCULATOR*);

#else /* K&R C */
extern bool_t xdr_CALCULATOR ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
