/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
#include <unistd.h>

void
calculator_prog_1(char *host)
{
	CLIENT *clnt;
	int  *number;
	char *get_num_1_arg;
	struct CALCULATOR  *result;
	struct CALCULATOR  calculator_proc_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULATOR_PROG, CALCULATOR_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	srand(getpid());
	while(1)
	{
		number = get_num_1((void*)&get_num_1_arg, clnt);
		if (number == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else{
			printf("number: %d ", *number);
		}
		
		sleep(rand() % 10 + 1);

		calculator_proc_1_arg.op = rand() % 4;
		calculator_proc_1_arg.arg1 = rand() % 10;
		calculator_proc_1_arg.arg2 = rand() % 10;
		calculator_proc_1_arg.number = *number;	

		result = calculator_proc_1(&calculator_proc_1_arg, clnt);
		
		printf("arg1: %f, arg2: %f, op: %d, res: %f", calculator_proc_1_arg.arg1, calculator_proc_1_arg.arg2, calculator_proc_1_arg.op, result->result);
		if (result == (struct CALCULATOR *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		else
		{
			if (result->return_code == 0)
				printf("result: %.2f\n", result->result);
			else if (result->return_code == 1)
				printf("too early\n");
			else if (result->return_code == 2)
			{
				printf("too late\n");
			}
			
		}
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculator_prog_1 (host);
exit (0);
}
